export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_REQUEST = "LOGIN_REQUEST";

export const REGISTER_FAILURE = "REGISTER_FAILURE"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_REQUEST = "REGISTER_REQUEST"

export const LOG_OUT = "LOG_OUT"

export const FORGOT_PASSWORD_FAILURE = "FORGOT_PASSWORD_FAILURE"
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS"
export const FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST"

export const RESET_PASSWORD_FAILURE = "RESET_PASSWORD_FAILURE"
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS"
export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST"