export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS"
export const CREATE_ORDER_FAILURE = "CREATE_ORDER_FAILURE"
export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST";

export const ORDER_STATUS_SUCCESS = "ORDER_STATUS_SUCCESS";
export const ORDER_STATUS_FAILURE = "ORDER_STATUS_FAILURE";
export const ORDER_STATUS_REQUEST = "ORDER_STATUS_REQUEST";

