export const GET_PRODUCTS_ALL_REQUEST = "GET_PRODUCTS_ALL_REQUEST";
export const GET_PRODUCTS_ALL_SUCCESS = "GET_PRODUCTS_ALL_SUCCESS";
export const GET_PRODUCTS_ALL_FAILURE = "GET_PRODUCTS_ALL_FAILURE";
export const SHOP_PRODUCTS_VIEW = "SHOP_PRODUCTS_VIEW";
export const FILTER_PRODUCT_SORT = "FILTER_PRODUCT_SORT"
export const SEARCH_PRODUCT = "SEARCH_PRODUCT"