export const OPEN_SIDEBAR = "OPEN_SIDEBAR";
export const DRAW_SIDEBAR = "DRAW_SIDEBAR";
export const DRAW_SIDEBAR_OPEN = "DRAW_SIDEBAR_OPEN";
export const DRAW_SIDEBAR_CLOSE = "DRAW_SIDEBAR_CLOSE";
export const IS_SHOW_CART = "IS_SHOW_CART";